import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import TopBanner from "@/components/TopBanner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`h-full ${inter.className}`}>
        <div className="min-h-screen flex flex-col">
          <TopBanner />
          <div className="flex-grow">
            <div className="max-w-7xl mx-auto px-5">
              <Header />
              <div className="flex-grow">{children}</div>
            </div>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
