// Generated by https://quicktype.io
// cool tool for quickly getting types ^^^

export interface Post {
  id: string;
  content_type_id: string;
  created_at: Date;
  updated_at: Date;
  created_by: null;
  updated_by: null;
  published: boolean;
  project_id: string;
  deleted: boolean;
  publish_at: null;
  published_at: null;
  metadata: Metadatum[];
  updatedBy: null;
  createdBy: null;
  slug: string;
  title: string;
  sections: Section[];
}

export interface Metadatum {
  id: string;
  name: string;
  type: string;
  value: string;
}

export interface Section {
  content_id: string;
  id: string;
  content_type: string;
  image?: Image[];
  imageMetadata?: any[];
  content?: string;
  images?: Image[];
}

export interface Image {
  id: string;
  created_at: Date;
  project_id: string;
  fileName: string;
  path: string;
  contentLength: number;
  mimeType: string;
  url: string;
}
// Generated by https://quicktype.io

export interface Dealer {
  id: string;
  content_type_id: string;
  created_at: Date;
  updated_at: Date;
  created_by: null;
  updated_by: null | string;
  published: boolean;
  project_id: string;
  deleted: boolean;
  publish_at: null;
  published_at: Date | null;
  metadata: any[];
  updatedBy: UpdatedBy | null;
  createdBy: null;
  lat?: number;
  lng?: number;
  city?: string;
  slug: string;
  email: string;
  phone?: string;
  title: string;
  address: string;
  country?: string;
  excerpt?: string;
  website?: string;
  continent?: Continent;
  contactName: string;
  description?: string;
  enginesRebuilt?: string;
  authorisedEngineRebuilder?: boolean;
  name?: string;
  crmIdentifier?: string;
  hash?: string;
  salt?: string;
  username?: string;
  heroImage?: HeroImage[];
}

export enum Continent {
  Americas = "Americas",
  Asia = "Asia",
  Europe = "Europe",
  MiddleEast = "Middle East",
  Oceania = "Oceania",
}

export interface HeroImage {
  id: string;
  created_at: Date;
  project_id: string;
  fileName: string;
  path: string;
  contentLength: number;
  mimeType: string;
  url: string;
}

export interface UpdatedBy {
  name: string;
  email: string;
}
